title: e-hulaserwis | Warszawa | Serwis
baseurl: ''
permalink: '/:title/'
color_scheme: light
accent_color: pink
header:
  has_nav: true
footer:
  content: '&copy; e-hulaserwis.pl. All rights reserved.'
  has_social: true
  links:
    - new_window: true
      text: Made with Stackbit by mw
      url: 'mwlodarski@icloud.com'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
defaults:
  - scope:
      path: ""
    values:
      image: /images/logo_dark.png
      author: Jacek Włodarski
full_url: https://e-hulaserwis.pl
