title: e-hulaserwis | Warszawa | Serwis
baseurl: ''
name: e-hulaserwis | Warszawa | Serwis
description: Serwis i modyfikacje Xiaomi M365
url: https://e-hulaserwis.pl
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
permalink: '/:title/'
color_scheme: light
accent_color: pink
header:
  has_nav: true
footer:
  content: '&copy; e-hulaserwis.pl. All rights reserved.'
  has_social: true
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-figure
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      is_post: true
      image: /images/logo_dark.png
      lang: pl
author:
  name: Jacek
default_locale: "pl"
lang: "pl"


